In [ ]:
myPackages <- c("dplyr", "tidyr")
lapply(myPackages, library, character.only = TRUE)
#the argument `lib.loc = "~/rlib"` is used because the packages were installed in this folder in my case
library(countrycode, lib.loc = "~/rlib")

# WEIRD COUNTRIES

US, Germany, UK, France, Canada, Italy, Australia, Spain, Iceland, Netherlands, Switzerland, Poland, Sweden, Belgium, Norway, Israel, Ireland, Austria, Denmark, Finland, Czech Republic, Portugal, Estonia, New Zealand, Luxembourg, Malta, Slovenia, Estonia, Lithuania, Slovakia, Trinidad and Tobago, Bahamas, Hungary

In [7]:
weirdCountry <- c("US", "Germany", "UK", "France", "Canada", "Italy", "Australia", "Spain", "Iceland", "Netherlands", "Switzerland", "Poland", "Sweden", "Belgium", "Norway", "Israel", "Ireland", "Austria", "Denmark", "Finland", "Czech Republic", "Portugal", "Estonia", "New Zealand", "Luxembourg", "Malta", "Slovenia", "Estonia", "Lithuania", "Slovakia", "Trinidad and Tobago", "Bahamas", "Hungary")

weirdDf <- data.frame(
    country = weirdName,
    iso3n = countrycode(weirdCountry, origin = "country.name" ,destination = "iso3n"),
    iso3c = countrycode(weirdCountry, origin = "country.name" ,destination = "iso3c"),
    iso2c = countrycode(weirdCountry, origin = "country.name" ,destination = "iso2c"))

weirdDf

   country             iso3n iso3c iso2c
1  US                  840   USA   US
2  Germany             276   DEU   DE
3  UK                  826   GBR   GB
4  France              250   FRA   FR
5  Canada              124   CAN   CA
6  Italy               380   ITA   IT
7  Australia            36   AUS   AU
8  Spain               724   ESP   ES
9  Iceland             352   ISL   IS
10 Netherlands         528   NLD   NL
11 Switzerland         756   CHE   CH
12 Poland              616   POL   PL
13 Sweden              752   SWE   SE
14 Belgium              56   BEL   BE
15 Norway              578   NOR   NO
16 Israel              376   ISR   IL
17 Ireland             372   IRL   IE
18 Austria              40   AUT   AT
19 Denmark             208   DNK   DK
20 Finland             246   FIN   FI
21 Czech Republic      203   CZE   CZ
22 Portugal            620   PRT   PT
23 Estonia             233   EST   EE
24 New Zealand         554   NZL   NZ
25 Luxembourg          442   LUX   LU
26 Malta               470   MLT   MT
27 Slovenia            705   SVN   SI
28 Estonia             233   EST   EE
29 Lithuania           440   LTU   LT
30 Slovakia            703   SVK   SK
31 Trinidad and Tobago 780   TTO   TT
32 Bahamas              44   BHS   BS
33 Hungary             348   HUN   HU

In [8]:
write.csv(weirdDf, "WEIRD_name_iso.csv", row.names = F)